/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java_2h;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class frameanggota extends javax.swing.JFrame {

    String[] Judulnya ={"ID Anggota","Nama Lengkap","Tempat Lahir","Tanggal Lahir","JKL","Status","Alamat","Telepon"};
    int[] LebarKolomFilm ={100,150,150,150,100,100,200,150};
    String SQL = "SELECT*FROM anggota";
    
    public frameanggota() {
        initComponents();
        this.setLocationRelativeTo(null);
        new configDB().setJudulKolom(TableAnggota,Judulnya);
        new configDB().setTampilTabel(TableAnggota, Judulnya, SQL);
        new configDB().setLebarJudulKolom(TableAnggota, LebarKolomFilm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txttempatlhr = new javax.swing.JTextField();
        txtjkl = new javax.swing.JTextField();
        txtstatus = new javax.swing.JTextField();
        txtalamat = new javax.swing.JTextField();
        txttelp = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableAnggota = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        txttanggallhr = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Anggota");

        jLabel2.setText("Nama Lengkap");

        jLabel3.setText("Tempat Lahir");

        jLabel4.setText("Tanggal Lahir");

        jLabel5.setText("JKL");

        jLabel6.setText("Status");

        jLabel7.setText("Alamat");

        jLabel8.setText("Telepon");

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Cetak");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        TableAnggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableAnggotaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableAnggota);

        jLabel9.setText("Cari Data");

        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCariKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(txtCari))
                    .addComponent(txtid)
                    .addComponent(txtnama)
                    .addComponent(txttempatlhr)
                    .addComponent(txtjkl)
                    .addComponent(txtstatus)
                    .addComponent(txtalamat)
                    .addComponent(txttelp)
                    .addComponent(txttanggallhr, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(78, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txttempatlhr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txttanggallhr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtjkl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txttelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      if (txtid.getText().equals("")){
                 JOptionPane.showMessageDialog(null,"ID Anggota Belum diisi");
                 txtid.requestFocus();
             }else if (txtnama.getText().equals("")){
                 JOptionPane.showMessageDialog(null,"Nama Belum diisi");
                 txtnama.requestFocus();
             }else if(txttempatlhr.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Tempat Lahir Belum diisi");
                 txttempatlhr.requestFocus();  
             }else if (txttanggallhr.getText().equals("")){
                  JOptionPane.showMessageDialog(null,"Tanggal Lahir Belum diisi");
                  txttanggallhr.requestFocus();
             }else if (txtjkl.getText().equals("")){
                  JOptionPane.showMessageDialog(null,"JKL Belum diisi");
                 txtjkl.requestFocus();
             }else if (txtstatus.getText().equals("")){
                  JOptionPane.showMessageDialog(null,"Status Belum diisi");
                 txtstatus.requestFocus();
             }else if (txtalamat.getText().equals("")){
                  JOptionPane.showMessageDialog(null,"Alamat Belum diisi");
                 txtalamat.requestFocus();
             }else if (txttelp.getText().equals("")){
                  JOptionPane.showMessageDialog(null,"Telepon Belum diisi");
                 txttelp.requestFocus();
             } else if (new configDB().getDuplikasiKey("anggota","IDAnggota",txtid.getText())){
                 JOptionPane.showMessageDialog(null,"ID Anggota sudah terdaftar");
             }else{
           // area koding simpan 
           
           String[] F = {"IDAnggota","nama","tempat_lahir","tgl_lahir","jkl","status","alamat","telp"};
           String[] isinya ={txtid.getText(),txtnama.getText(),txttempatlhr.getText(),txttanggallhr.getText(),txtjkl.getText(),txtstatus.getText(),txtalamat.getText(),txttelp.getText()};
           new configDB().SimpanDinamis("anggota", F, isinya);
           
            new configDB().setJudulKolom(TableAnggota,Judulnya);
            new configDB().setTampilTabel(TableAnggota, Judulnya, SQL);
            new configDB().setLebarJudulKolom(TableAnggota, LebarKolomFilm);
             }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String tid = txtid.getText();
        String tnama= txtnama.getText();
        String ttempat= txttempatlhr.getText();
        String ttanggal= txttanggallhr.getText();
        String tjkl = txtjkl.getText();
        String tstatus = txtstatus.getText();
        String talamat = txtalamat.getText();
        String ttelp = txttelp.getText();
        
        String[] fieldnya ={"nama","tempat_lahir","tgl_lahir","jkl","status","alamat","telp"};
        String[]isinya ={tnama,ttempat,ttanggal,tjkl,tstatus,talamat,ttelp};
        
        new configDB().UbahDinamis("anggota", "IDAnggota", tid, fieldnya, isinya);
        
        new configDB().setJudulKolom(TableAnggota,Judulnya);
        new configDB().setTampilTabel(TableAnggota, Judulnya, SQL);
        new configDB().setLebarJudulKolom(TableAnggota, LebarKolomFilm);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     new configDB().HapusDinamis("anggota", "IDAnggota", txtid.getText());
     new configDB().setJudulKolom(TableAnggota,Judulnya);
     new configDB().setTampilTabel(TableAnggota, Judulnya, SQL);
     new configDB().setLebarJudulKolom(TableAnggota, LebarKolomFilm);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void TableAnggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableAnggotaMouseClicked
       int row = TableAnggota.getSelectedRow();
        txtid.setText(TableAnggota.getModel().getValueAt(row,0).toString());
        txtnama.setText(TableAnggota.getModel().getValueAt(row,1).toString());
        txttempatlhr.setText(TableAnggota.getModel().getValueAt(row,2).toString());
        txttanggallhr.setText(TableAnggota.getModel().getValueAt(row,3).toString());
        txtjkl.setText(TableAnggota.getModel().getValueAt(row,4).toString());
        txtstatus.setText(TableAnggota.getModel().getValueAt(row,5).toString());
        txtalamat.setText(TableAnggota.getModel().getValueAt(row,6).toString());
        txttelp.setText(TableAnggota.getModel().getValueAt(row,7).toString());
    }//GEN-LAST:event_TableAnggotaMouseClicked

    private void txtCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyPressed
     String SQLCari ="SELECT*FROM anggota WHERE IDAnggota LIKE '%"+txtCari.getText()+"%' OR nama LIKE '%"+txtCari.getText()+"%' ";
      new configDB().setJudulKolom(TableAnggota, Judulnya);
      new configDB().cariData(TableAnggota, Judulnya,SQLCari);
      new configDB().setLebarJudulKolom(TableAnggota, LebarKolomFilm);
    }//GEN-LAST:event_txtCariKeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
   new configDB().tampilLaporan("src/laporan/Lapanggota.jrxml","SELECT*FROM anggota");
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameanggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameanggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameanggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameanggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameanggota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableAnggota;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtjkl;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtstatus;
    private javax.swing.JTextField txttanggallhr;
    private javax.swing.JTextField txttelp;
    private javax.swing.JTextField txttempatlhr;
    // End of variables declaration//GEN-END:variables
}
